spring:
  application:
    name: application_server

  datasource:
    username: ${mysql.user}
    password: ${mysql.pw}
    url: jdbc:mysql://localhost:3306/artu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # 서버가 무슨 sql 쓰는지 알려주는 설정

server:
  port: 8181


